# ============================================================
# Keepalived – Nodo BACKUP
# Instalación en Ubuntu/Debian:
#   sudo apt install keepalived
#   sudo cp keepalived-backup.conf /etc/keepalived/keepalived.conf
#   sudo systemctl enable keepalived && sudo systemctl start keepalived
#
# Este archivo es IDÉNTICO al del MASTER excepto por:
#   state    → BACKUP
#   priority → 100  (menor que MASTER = 101)
# ============================================================

vrrp_script check_nginx {
    script "pgrep nginx"
    interval 2
    weight   2
    fall     2
    rise     1
}

vrrp_instance VI_TECHSTORE {
    state  BACKUP
    interface eth0                # ← cambiá por tu interfaz
    virtual_router_id 51          # Debe ser igual que en MASTER
    priority  100                 # Menor que MASTER (101)
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass techstore360    # ← misma contraseña que MASTER
    }

    virtual_ipaddress {
        192.168.1.100/24          # ← misma VIP que MASTER
    }

    track_script {
        check_nginx
    }
}
